import { v4 as uuidv4 } from 'uuid'

/**
 * Webpack
 *
 * Demonstrates how webpack can be used when developing external plugins.
 *
 * All information regarding plugin development can be found at
 * https://dev.spatialweb.net/plugins/plugins/
 *
 * @license MIT
 * @author Vatom Inc.
 */
export default class WebpackImport extends BasePlugin {

    /** Plugin info */
    static id = 'vatominc-webpack-showcase'
    static name = 'Webpack Showcase'
    static description = 'A plugin that includes an npm library bundled with Webpack.'

    /** Called on load */
    onLoad() {

        // Show alert
        this.menus.alert('Webpack plugin has been loaded! Here is a UUID generated by an external library: ' + uuidv4(), 'Webpack Showcase', 'info')

    }

}
